import { Book, FileText, GraduationCap, Award } from 'lucide-react';

export const profileData = {
  // --- KİŞİSEL BİLGİLER ---
  personal: {
    name: "Prof. Dr. Erdal Bay",
    title: "Eğitim Programları ve Öğretim Anabilim Dalı",
    university: "Gaziantep Üniversitesi",
    faculty: "Gaziantep Eğitim Fakültesi",
    email: "erdalbay@gantep.edu.tr",
    phone: "(0342) 360 12 00",
    extension: "3785",
    image: "https://duysis.gaziantep.edu.tr/upload/profile_photo/45064-8.jpg",
    bio: "Gaziantep Üniversitesi Eğitim Fakültesi Eğitim Bilimleri Bölümü'nde Profesör olarak görev yapmaktadır. Eğitim Programları ve Öğretim, Eğitim Politikaları ve Eğitimin Sosyal Tarihi Temelleri üzerine uzmanlaşmıştır.",
  },

  // --- İSTATİSTİKLER ---
  stats: [
    { label: "Kitap & Bölüm", value: "20", icon: Book },
    { label: "Makale", value: "74", icon: FileText },
    { label: "Bildiri", value: "68", icon: GraduationCap },
    { label: "Proje", value: "37", icon: Award },
  ],

  // --- EĞİTİM BİLGİLERİ ---
  education: [
    { year: "2023 - Devam", degree: "Lisans (İkinci Üniversite)", school: "Anadolu Üniversitesi", field: "Siyaset Bilimi ve Kamu Yönetimi" },
    { year: "2003 - 2008", degree: "Doktora", school: "Atatürk Üniversitesi", field: "Eğitim Programları ve Öğretimi" },
    { year: "2000 - 2003", degree: "Yüksek Lisans", school: "Atatürk Üniversitesi", field: "Eğitim Programları ve Öğretimi" },
    { year: "1995 - 2000", degree: "Lisans", school: "Atatürk Üniversitesi", field: "Eğitim Bilimleri" }
  ],

  // --- EKSİK OLAN: AKADEMİK GEÇMİŞ ---
  experience: [
    { year: "2021 - 2022", title: "Profesör", place: "Gaziantep Üniversitesi / Eğitim Fakültesi" },
    { year: "2020 - 2021", title: "Profesör", place: "Gaziantep İslam Bilim ve Teknoloji Üniversitesi" },
    { year: "2012 - 2020", title: "Doçent", place: "Gaziantep Üniversitesi" },
    { year: "2010 - 2012", title: "Yardımcı Doçent", place: "Gaziantep Üniversitesi" },
    { year: "2010 - 2010", title: "Yardımcı Doçent", place: "Atatürk Üniversitesi" },
    { year: "2008 - 2010", title: "Araştırma Görevlisi", place: "Atatürk Üniversitesi" },
    { year: "2001 - 2008", title: "Araştırma Görevlisi", place: "Atatürk Üniversitesi" },
  ],

  // --- İDARİ GÖREVLER (Güncellenmiş Tam Liste) ---
  administrative: [
    { role: "Fakülte Kurulu Üyeliği", place: "Gaziantep Üniversitesi", year: "2023 - Devam" },
    { role: "Kalite Kurulu Üyeliği", place: "Gaziantep Üniversitesi", year: "2023 - Devam" },
    { role: "Yönetim Kurulu Üyeliği", place: "Gaziantep Üniversitesi", year: "2023 - Devam" },
    { role: "Arş. Uyg. Merkezi Müdürü", place: "Gaziantep Üniversitesi", year: "2022 - 2025" },
    { role: "Dekan", place: "Gaziantep Üniversitesi", year: "2021 - 2025" },
    { role: "Senatör", place: "Gaziantep Üniversitesi", year: "2021 - 2025" },
    { role: "Yönetim Kurulu Üyeliği", place: "Gaziantep Üniversitesi", year: "2021 - 2025" },
    { role: "Fakülte Yönetim Kurulu Üyeliği", place: "Gaziantep Üniversitesi", year: "2021 - Devam" },
    { role: "Teknoloji Transfer Ofisi YK Üyesi", place: "Gaziantep Üniversitesi", year: "2020 - 2025" },
    { role: "Komisyon Üyeliği", place: "Gaziantep Üniversitesi", year: "2022 - 2024" },
    { role: "Fakülte Yönetim Kurulu Üyeliği", place: "Gaziantep Üniversitesi", year: "2022 - 2023" },
    { role: "Rektör Vekaleti", place: "Gaziantep İslam Bilim ve Teknoloji Üni.", year: "2020" },
    { role: "ÜAK Üyeliği", place: "Gaziantep İslam Bilim ve Teknoloji Üni.", year: "2020" },
    { role: "Anabilim Dalı Başkanı", place: "Gaziantep Üniversitesi", year: "2014 - 2017" },
    { role: "Yönetim Kurulu Üyeliği", place: "Gaziantep Üniversitesi", year: "2014 - 2016" },
    { role: "Dekan Yardımcısı", place: "Gaziantep Üniversitesi", year: "2012 - 2014" },
    { role: "Eğitim Koordinatörü", place: "Gaziantep Üniversitesi", year: "2012 - 2013" }
  ],

  // --- EKSİK OLAN: ÖDÜLLER ---
  awards: [
    { title: "Manas Türk Dünyası Hizmet Belgesi", year: "2021", org: "Kırgızistan-Türkiye Manas Üniversitesi" },
    { title: "Bilge Tonyukuk Türk Eğitimine Hizmet Ödülü", year: "2020", org: "UAESEB" },
    { title: "Korkut Türk Eğitimine Hizmet Ödülü", year: "2019", org: "UAESEB" },
    { title: "Türk Dünyası Hizmet Ödülü", year: "2017", org: "Ülkü Ocakları" },
    { title: "Türk Dünyası Ödülü", year: "2016", org: "TURKSAV" },
    { title: "Yayın Teşvik Ödülü", year: "2014", org: "TÜBİTAK" }
  ],

  // --- 1. KATEGORİ: KİTAPLAR ---
  books: [
    { id: "k1", type: "Uluslararası Bilimsel Kitap", title: "Etnopedagojik Bağlamda Balkan Ülkeleri ve Türkiye Okul öncesi Ethosferinde Karakter Eğitimi", authors: "ERİŞEN YAVUZ, BAY ERDAL, KAYA NACİYE", publisher: "PEGEM AKADEMİ", year: "2024", isbn: "978-625-6287-58-7" },
    { id: "k2", type: "Uluslararası Bilimsel Kitap", title: "Eğitimde Program Geliştirme", chapter: "Öğretim Programlarının Kuramsal Temelleri", authors: "ŞİRAZ FADIL, BAY ERDAL", publisher: "PEGEM AKADEMİ", year: "2023", isbn: "978-625-6810-87-7" },
    { id: "k3", type: "Uluslararası Bilimsel Kitap", title: "Dünya Ülkelerinden Örneklerle Karşılaştırmalı Eğitim ve Öğretmen Yetiştirme Sistemlerine Bakış I", chapter: "Azerbaycan Eğitim ve Öğretmen Yetiştirme Sistemleri", authors: "ŞİRAZ FADIL, BAY ERDAL", publisher: "PEGEM AKADEMİ", year: "2023", isbn: "978-625-6810-88-4" },
    { id: "k4", type: "Uluslararası Bilimsel Kitap", title: "Z Kuşağı Ethosfer Sisteminin Analizi (Z’amane Kuşağını Anlama)", chapter: "Fenomen Analizi", authors: "BAŞARAN MEHMET, BAY ERDAL", publisher: "Gazi Kültür", year: "2023", isbn: "978-6257518-23-9" },
    { id: "k5", type: "Uluslararası Bilimsel Kitap", title: "Etkili Öğretim Stratejileri", chapter: "Etkili Soru Sorma Yaklaşımı", authors: "KAHRAMANOĞLU RECEP, BAY ERDAL", publisher: "PEGEM AKADEMİ", year: "2022", isbn: "978-625-7228-12-1" },
    { id: "k6", type: "Uluslararası Bilimsel Kitap", title: "Etkili Öğretim Stratejileri", chapter: "Benzerlikler ve Farlılıklar Stratejisi", authors: "DUMAN Cevahir, BAY ERDAL", publisher: "PEGEM", year: "2022", isbn: "978-625-7228-12-1" },
    { id: "k7", type: "Uluslararası Bilimsel Kitap", title: "Bilgisayarsız Kodlama Eğitiminde Bilgi İşlemsel Düşünme", authors: "ÜZÜMCÜ ÖZLEM, BAY ERDAL", publisher: "Akademisyen", year: "2021", isbn: "978-625-7409-58-2" },
    { id: "k8", type: "Uluslararası Bilimsel Kitap", title: "Öğretimde Yaklaşımlar ve Eğitime Yansımaları", chapter: "Otantik Öğrenme", authors: "AYDIN ZEYNEP, KARAKOÇ BERNA, BAY ERDAL", publisher: "Pegem Akademi", year: "2020", isbn: "978-625-7228-34-3" },
    { id: "k9", type: "Uluslararası Bilimsel Kitap", title: "Erken Çocukluk Döneminde Fen Eğitimi", chapter: "Erken Çocukluk Dönemi Fen Eğitiminde Stem Yaklaşımı", authors: "BAŞARAN MEHMET, BAY ERDAL", publisher: "Nobel", year: "2020", isbn: "978-605-033-232-2" },
    { id: "k10", type: "Uluslararası Bilimsel Kitap", title: "Eğitim Sosyolojisi", chapter: "Sosyal ahlaki ve kültürel bir kurum olarak okul", authors: "BAY ERDAL, DÖŞ BÜLENT", publisher: "Pegem", year: "2019", isbn: "978-605-241-421-7" },
    { id: "k11", type: "Ulusal Bilimsel Kitap", title: "Eğitim Sosyolojisi", chapter: "Sosyal Kültürel ve Ahlaki Bir Kurum Olarak Okul", authors: "BAY ERDAL, DÖŞ BÜLENT", publisher: "Pegem Akademi", year: "2018", isbn: "978-605-241-421-7" },
    { id: "k12", type: "Uluslararası Araştırma Kitabı", title: "Türk Dünyasının Eğitim Sistemleri ve Sorunları", chapter: "Kosova Eğitim Sistemi", authors: "Bedrettin KORO, Serdan Kervan, BAY ERDAL", publisher: "pegem akademi", year: "2017", isbn: "978-605-241-157-5" },
    { id: "k13", type: "Ulusal Ders Kitabı", title: "Eğitim Bilimine Giriş", chapter: "Eğitim ve Felsefe", authors: "KINCAL REMZİ YAVAŞ, BAY ERDAL", publisher: "Grafiker Yayınevi", year: "2017" },
    { id: "k14", type: "Ulusal Bilimsel Kitap", title: "Reform ve değişim Bağlamında İlkokul Matematik Öğretim Programları", chapter: "Cumhuriyet Döneminden Günümüze Eğitim Sistemimiz", authors: "ERGÜN MUSTAFA, BAY ERDAL", publisher: "PEGEM", year: "2016", isbn: "978-605-318-335-8" },
    { id: "k15", type: "Ulusal Bilimsel Kitap", title: "Reform ve değişim Bağlamında İlkokul Matematik Öğretim Programları", chapter: "Cumhuriyet Dönemi Matematik Öğretim Programlarının Değerlendirilmesi", authors: "ÇIRAK SEVİLAY, BAY ERDAL", publisher: "PEGEM", year: "2016" },
    { id: "k16", type: "Ulusal Ders Kitabı", title: "Eğitim Sosyolojisi", chapter: "Toplumsal Değişme ve Eğitim", authors: "BAY ERDAL, DÖŞ BÜLENT", publisher: "Atatürk Üniversitesi", year: "2016", isbn: "978-975-442-815-5" },
    { id: "k17", type: "Ulusal Bilimsel Kitap", title: "TÜRKSAV Türk Dünyası 25 Yıllığı", chapter: "Türk Dünyası Vatandaşlığı", authors: "BAY ERDAL, AKDAĞ HAKAN", publisher: "Akçağ", year: "2016" },
    { id: "k18", type: "Ulusal Ders Kitabı", title: "Öğretim İlke ve Yöntemleri", chapter: "Eğitimde yapılandırmacılık", authors: "BAY ERDAL", publisher: "Atatürk Üniversitesi", year: "2014" },
    { id: "k19", type: "Ulusal Bilimsel Kitap", title: "Eğitim Bilimine Giriş", chapter: "Eğitim Bilimleri ile İlgili Temel Kavramlar", authors: "BAY ERDAL", publisher: "Grafiker yayın", year: "2011" },
    { id: "k20", type: "Ulusal Bilimsel Kitap", title: "Eğitim Bilimine Giriş", chapter: "Eğitimin felsefi temelleri", authors: "BAY ERDAL", publisher: "Lisans yayıncılık", year: "2007" }
  ],

  // --- 2. KATEGORİ: MAKALELER ---
  articles: [
    { id: "m1", type: "Makale (SSCI Q2)", title: "The effect of project-based STEAM activities on the social and cognitive skills of preschool children", authors: "BAŞARAN MEHMET, BAY ERDAL", publisher: "Informa UK Limited", year: "2023" },
    { id: "m2", type: "Makale", title: "An Analysis of the Studies Conducted in the Field of Curriculum Evaluation", authors: "DOĞAN ESRA, BAY ERDAL, DÖŞ BÜLENT", publisher: "Canadian Center of Science and Education", year: "2023" },
    { id: "m3", type: "Makale", title: "A cross-cultural study on American, German and Turkish Classroom teachers opinions about character education", authors: "GÜNDOĞDU KERİM, BAY ERDAL", publisher: "Psycho-Educational Research Reviews", year: "2022" },
    { id: "m4", type: "Makale", title: "Etnopedagojik Bağlamda Kuzey Makedonya ve Türkiye Okul Öncesi Eğitim Programlarında Karakter Eğitimi", authors: "KAYA NACİYE, BAY ERDAL", publisher: "Türkiye Eğitim Dergisi", year: "2022" },
    { id: "m5", type: "Makale (TR DİZİN)", title: "Benzerlikler ve Farlılıklar Stratejisinin Öğrenci Başarısı Üzerindeki Etkisinin İncelenmesi", authors: "DUMAN CEVAHİR, BAY ERDAL", publisher: "Atatürk Üniversitesi Dergisi", year: "2022" },
    { id: "m6", type: "Makale (ERIH PLUS)", title: "POLITICAL FOUNDATIONS OF SOCIAL STUDIES CURRICULA IN THE CONTEXT OF CITIZENSHIP EDUCATION", authors: "Şiraz Fadıl, BAY ERDAL", publisher: "European Journal of Education Studies", year: "2021" },
    { id: "m7", type: "Makale (TR DİZİN)", title: "OKUL ÖNCESİ ETHOSFERİNDE KARAKTER EĞİTİMİNE İLİŞKİN MEVCUT DURUMUN ANALİZİ", authors: "KOCALAR EVRİM, BAY ERDAL", publisher: "Abant İzzet Baysal Üniversitesi", year: "2021" },
    { id: "m8", type: "Makale", title: "AN ANALYSIS OF TURKISH AND RUSSIAN TEACHERS’ OF ENGLISH APPROACHES TO EFFECTIVE INSTRUCTIONAL STRATEGIES", authors: "Çelik Aleksandra, BAY ERDAL", publisher: "Psycho-Educational Research Reviews", year: "2021" },
    { id: "m9", type: "Makale (SSCI Q1)", title: "The effect of computational thinking skill program design developed according to interest driven creator theory", authors: "ÜZÜMCÜ ÖZLEM, BAY ERDAL", publisher: "Education and Information Technologies", year: "2021" },
    { id: "m10", type: "Makale", title: "Understanding the Social Studies Curricula in Turkey as a Political Text", authors: "Şiraz Fadıl, BAY ERDAL", publisher: "International Education Studies", year: "2021" },
    { id: "m11", type: "Makale", title: "THE REASONS FOR GAINING AND LOSING THE POPULARITY OF A PARADIGM IN CONSTRUCTIVISM", authors: "BAY ERDAL, BAŞARAN MEHMET", publisher: "Psycho-Educational Research Reviews", year: "2021" },
    { id: "m12", type: "Makale (TR DİZİN)", title: "Siyasi Partilerin Seçim Beyannamelerinde Hedeflediği İnsan Karakterlerinin Analizi", authors: "BAY ERDAL, KAHRAMANOĞLU RECEP", publisher: "OPUS Uluslararası Toplum Araştırmaları", year: "2020" },
    { id: "m13", type: "Makale", title: "Vatandaşlık Eğitimi Bağlamında 1998, 2005 ve 2018 Sosyal Bilgiler Öğretim Programları Analizi", authors: "ŞİRAZ FADIL, BAY ERDAL", publisher: "Anadolu Türk Eğitim Dergisi", year: "2020" },
    { id: "m14", type: "Makale (TR DİZİN)", title: "2013 Okul Öncesi Eğitim Programının Karakter Eğitimi Açısından Değerlendirilmesi", authors: "KOCALAR EVRİM, BAY ERDAL", publisher: "İnönü Üniversitesi", year: "2020" },
    { id: "m15", type: "Makale (TR DİZİN)", title: "İngilizce öğretmenlerinin Eğitim Bilişim Ağı (EBA) kullanım durumlarının incelenmesi", authors: "KULOĞLU MUHAMMET ESAD, BAY ERDAL", publisher: "Milli Eğitim Dergisi", year: "2019" },
    { id: "m16", type: "Makale", title: "Eğitimde Yeni 21. Yüzyıl Becerisi: Bilgi İşlemsel Düşünme", authors: "ÜZÜMCÜ ÖZLEM, BAY ERDAL", publisher: "Uluslararası Türk Kültür Coğrafyası", year: "2018" },
    { id: "m17", type: "Makale", title: "Dil Olarak İngilizce Öğretiminde Etkili Öğretim Stratejilerinin Kullanımının Analizi", authors: "altunöz hatun buğra, BAY ERDAL", publisher: "TURKSOSBİLDER", year: "2018" },
    { id: "m18", type: "Makale", title: "7. Sınıf Matematik Dersinde Otantik Görev Odaklı Öğrenme Süreçleri", authors: "aşk aydın zeynep, BAY ERDAL", publisher: "Adnan Menderes Üniversitesi", year: "2018" },
    { id: "m19", type: "Makale", title: "Etkili Öğretim Stratejileri Ölçeği’nin Geliştirilmesi (EÖSÖ)", authors: "CÜCÜK EYÜP, BAY ERDAL", publisher: "Elektronik Sosyal Bilimler Dergisi", year: "2018" },
    { id: "m20", type: "Makale (TR DİZİN)", title: "Programa Bağlılığı Etkileyen Faktörlerin Analizi", authors: "BAY ERDAL, KAHRAMANOĞLU RECEP", publisher: "MAKÜ", year: "2017" },
    { id: "m21", type: "Makale (ESCI)", title: "Türk Dünyası Birliği Algısı", authors: "BAY ERDAL, AKMATALİ ALİBEKOV", publisher: "Gazi Akademik Bakış", year: "2017" },
    { id: "m22", type: "Makale", title: "Sekizinci Sınıf Matematik Öğretiminde Teori ve Uygulama Bağlamında Program Uyumluluğu", authors: "kara kevser, BAY ERDAL", publisher: "Harran Eğitim Dergisi", year: "2017" },
    { id: "m23", type: "Makale", title: "Analyzing the curriculum alignment of teachers", authors: "TURAN ÖZPOLAT ESEN, BAY ERDAL", publisher: "Universal Journal of Educational Research", year: "2017" },
    { id: "m24", type: "Makale (TR DİZİN)", title: "Tanzimat’tan Cumhuriyet’e Osmanlı’da Öğretmen Yetiştiren Kurumlar", authors: "CÜCÜK EYÜP, BAY ERDAL", publisher: "Gaziantep Üniversitesi", year: "2017" },
    { id: "m25", type: "Makale", title: "Examination of “Curriculum Alignment” in the Context of Theory and Practice", authors: "Kara Kevser, BAY ERDAL", publisher: "Harran Education Journal", year: "2017" },
    { id: "m26", type: "Makale (ULAKBİM)", title: "Fen Bilimleri Dersinde Etkili Öğretim Stratejilerinin Etkililiğinin Değerlendirilmesi", authors: "kara kevser, BAY ERDAL", publisher: "Atatürk Üniversitesi", year: "2017" },
    { id: "m27", type: "Makale (TR DİZİN)", title: "Okul temelli program geliştirme yaklaşımına ilişkin öğretmen görüşleri", authors: "BAY ERDAL, VURAL ÖMER FARUK", publisher: "Mustafa Kemal Üniversitesi", year: "2016" },
    { id: "m28", type: "Makale", title: "Developing a Scale on Factors Regarding Curriculum Alignment", authors: "BAY ERDAL", publisher: "Journal of Education and Training Studies", year: "2016" },
    { id: "m29", type: "Makale (SSCI)", title: "Determination of Admittance Standards for Teacher Training Institutions", authors: "KAHRAMANOĞLU RECEP, BAY ERDAL", publisher: "Education and Science", year: "2016" },
    { id: "m30", type: "Makale", title: "An analysis of teachers questioning strategies", authors: "DÖŞ BÜLENT, BAY ERDAL", publisher: "Educational Research and Reviews", year: "2016" },
    { id: "m31", type: "Makale", title: "Opinions of the Teachers Related with the Positive and Negative Aspects of the Authentic Task", authors: "Karakoç Berna, BAY ERDAL", publisher: "Journal of Education and Learning", year: "2016" },
    { id: "m32", type: "Makale (TR DİZİN)", title: "Kuantum öğrenme döngüsü ile desteklenen harmanlanmış öğrenme", authors: "ÇIRAK SEVİLAY, BAY ERDAL", publisher: "Mustafa Kemal Üniversitesi", year: "2016" },
    { id: "m33", type: "Makale", title: "Kültürlerarası bağlamda Türk Dünyası Vatandaşlığı projesi geliştirilmesi", authors: "BAY ERDAL, DEMİR SERVET", publisher: "TEKE", year: "2015" },
    { id: "m34", type: "Makale", title: "Changes in the Beliefs of the Prospective Teachers on Knowledge Learning", authors: "BAY ERDAL, VURAL ÖMER FARUK", publisher: "Gaziantep Üniversitesi", year: "2015" },
    { id: "m35", type: "Makale", title: "Program uyumluluğu ve program uyumluluğunu etkileyen faktörler", authors: "esen Özpolat Turan, BAY ERDAL", publisher: "Route Educational Journal", year: "2015" },
    { id: "m36", type: "Makale", title: "Okul temelli yaklaşımla geliştirilen değer eğitim programının etkililiği", authors: "ÖZYURT MELİKE, BAY ERDAL", publisher: "Ege Eğitim Dergisi", year: "2015" },
    { id: "m37", type: "Makale", title: "An analysis of Candidate teachers beliefs related to knowledge learning", authors: "BAY ERDAL, VURAL ÖMER FARUK", publisher: "International Education Studies", year: "2015" },
    { id: "m38", type: "Makale", title: "A Study on Possible Assessment Methods for Admission Standards", authors: "KAHRAMANOĞLU RECEP, BAY ERDAL", publisher: "Uluslararası Eğitim Programları Dergisi", year: "2015" },
    { id: "m39", type: "Makale", title: "Öğretmen Yetiştiren Kurumlara Öğrenci Seçiminde Kullanılacak Giriş Standartları", authors: "kahramanoğlu recep, BAY ERDAL", publisher: "Uluslararası Eğitim Programları Dergisi", year: "2015" },
    { id: "m40", type: "Makale (SSCI)", title: "An Examination Of Teachers Beliefs About Learning", authors: "BAY ERDAL, İLHAN MUSTAFA", publisher: "Croatian Journal of Education", year: "2014" },
    { id: "m41", type: "Makale", title: "Sınıf öğretmenlerinin çoklu zekâ kuramına ilişkin görüşleri", authors: "OZAN CEYHUN, BAY ERDAL", publisher: "Türk Eğitim Bilimleri Dergisi", year: "2013" },
    { id: "m42", type: "Makale", title: "4 4 4 modelinin paydaşlar bağlamında değerlendirilmesi", authors: "BAY ERDAL, TÜRKAN AZMİ", publisher: "Eğitim ve Toplum Dergisi", year: "2013" },
    { id: "m43", type: "Makale (Scopus)", title: "Evaluation of secondary education programs in the context of social foundations", authors: "BAY ERDAL, celkan H Y", publisher: "Procedia - Social and Behavioral Sciences", year: "2012" },
    { id: "m44", type: "Makale (Scopus)", title: "Self regulatory learning strategy skills and self efficacy perceptions", authors: "OZAN CEYHUN, BAY ERDAL", publisher: "Procedia", year: "2012" },
    { id: "m45", type: "Makale", title: "Öğrenmeye yönelik inanç ölçeği Geçerlik ve güvenirlik çalışması", authors: "BAY ERDAL, İLHAN MUSTAFA", publisher: "Uluslararası İnsan Bilimleri Dergisi", year: "2012" },
    { id: "m46", type: "Makale", title: "Eski Türk Eserlerine İlişkin Tutum Ölçeği Geliştirilmesi", authors: "BAY ERDAL, MERT OSMAN", publisher: "Uluslararası Türkçe Edebiyat Kültür Eğitim Dergisi", year: "2012" },
    { id: "m47", type: "Makale", title: "İşbirliği süreci ölçeği İSÖ geliştirilmesi", authors: "ÇETİN BAYRAM, BAY ERDAL", publisher: "Uluslararası İnsan Bilimleri Dergisi", year: "2012" },
    { id: "m48", type: "Makale", title: "Analyse of efficiency of cooperatıve process ın socıal constructıvıst", authors: "BAY ERDAL, ÇETİN BAYRAM", publisher: "IJHSS", year: "2012" },
    { id: "m49", type: "Makale", title: "The effects social constructivist approach on the learners problem solving", authors: "BAY ERDAL, ÇETİN BAYRAM", publisher: "Journal of Social Sciences", year: "2012" },
    { id: "m50", type: "Makale", title: "İlköğretim öğretmen adaylarının program yaklaşımlarının analizi", authors: "BAY ERDAL, GÜNDOĞDU KERİM", publisher: "Uluslar arası Eğitim Programları Dergisi", year: "2012" },
    { id: "m51", type: "Makale", title: "Perceptions of prospective early childhood teachers in relation to violence", authors: "koçyiğit s, BAY ERDAL", publisher: "Mediterranean Journal", year: "2011" },
    { id: "m52", type: "Makale (SSCI)", title: "Examination of the impact of rubric use on achievement in teacher education", authors: "BAY ERDAL, KOTAMAN HÜSEYİN", publisher: "New Educational Review", year: "2011" },
    { id: "m53", type: "Makale", title: "İlköğretim 6-8 sınıflarda ortaya çıkan istenmeyen öğrenci davranışları", authors: "BAY ERDAL, MERT OSMAN", publisher: "Kazım Karabekir Eğitim Fakültesi Dergisi", year: "2011" },
    { id: "m54", type: "Makale", title: "The Opinions of Prospective Teachers about Peer Assessment", authors: "BAY ERDAL", publisher: "Gaziantep Üniversitesi Dergisi", year: "2011" },
    { id: "m55", type: "Makale", title: "Development of learner roles in constructive learning environment scale", authors: "BAY ERDAL", publisher: "Electronic Journal Of Research In Educational Psychology", year: "2011" },
    { id: "m56", type: "Makale", title: "Demokratik yapılandırmacı öğrenme ortamı ölçeği geliştirilmesi", authors: "BAY ERDAL, KAYA HALİL İBRAHİM", publisher: "Journal of New World Sciences Academy", year: "2010" },
    { id: "m57", type: "Makale", title: "Sınıf Öğretmeni Adaylarının Öğretmenlik Uygulamasına İlişkin Görüşleri", authors: "GÜNDOĞDU KERİM, BAY ERDAL", publisher: "Bayburt Üniversitesi Dergisi", year: "2010" },
    { id: "m58", type: "Makale", title: "The perceptions of prospective teachers on the democratic aspects", authors: "BAY ERDAL, GÜNDOĞDU KERİM", publisher: "Electronic Journal Of Research", year: "2010" },
    { id: "m59", type: "Makale", title: "Öğrenme ve değişim", authors: "BAY ERDAL, KARAKAYA ŞERAFETTİN", publisher: "Yakın Doğu Sosyal Bilimler Dergisi", year: "2010" },
    { id: "m60", type: "Makale", title: "The perception of the families and teachers towards undesired behaviors", authors: "BAY ERDAL", publisher: "Mediterranean Journal", year: "2009" },
    { id: "m61", type: "Makale", title: "Orhun yazıtlarındaki toplumsal değerlerin algılanma düzeyi", authors: "MERT OSMAN, BAY ERDAL", publisher: "Uluslararası Sosyal Araştırmalar Dergisi", year: "2009" },
    { id: "m62", type: "Makale", title: "Öğretmen eğitiminde yapılandırmacı yaklaşıma dayalı uygulamalar", authors: "BAY ERDAL, KARAKAYA ŞERAFETTİN", publisher: "Elektronik Sosyal Bilimler Dergisi", year: "2009" },
    { id: "m63", type: "Makale", title: "Öğretmen adaylarının otantik görevlere ilişkin görüşlerinin incelenmesi", authors: "BAY ERDAL, KARAKAYA ŞERAFETTİN", publisher: "Çağdaş Eğitim Dergisi", year: "2009" },
    { id: "m64", type: "Makale", title: "The perceptions of prospective teachers in relation to teacher roles", authors: "BAY ERDAL, KAYA HALİL İBRAHİM", publisher: "Mediterranean Journal", year: "2009" },
    { id: "m65", type: "Makale", title: "Okul öncesi dönem çocuklarında görülen sorunların değerlendirilmesi", authors: "KÖK MEHMET, BAY ERDAL", publisher: "Kazım Karabekir Eğitim Fakültesi Dergisi", year: "2008" },
    { id: "m66", type: "Makale", title: "İlköğretim 2. Kademe öğrencilerinin beden eğitimi ve spor dersleri görüşleri", authors: "ŞİRİNKAN AHMET, BAY ERDAL", publisher: "Beden Eğitimi Dergisi", year: "2007" },
    { id: "m67", type: "Makale", title: "Ortaöğretim öğrencilerinin beden eğitimi öğretmenleri ile iletişimleri", authors: "ŞİRİNKAN AHMET, BAY ERDAL", publisher: "Beden Eğitimi Dergisi", year: "2007" },
    { id: "m68", type: "Makale", title: "Öğretim elemanlarının ders verdikleri öğrencilerin özelliklerine ilişkin görüşleri", authors: "KAYA HALİL İBRAHİM, BAY ERDAL", publisher: "Atatürk Üniversitesi Dergisi", year: "2007" },
    { id: "m69", type: "Makale", title: "Program değerlendirme sürecinde karşılaşılan sorunlar", authors: "BAY ERDAL, KARAKAYA ŞERAFETTİN", publisher: "Kazım Karabekir Dergisi", year: "2006" },
    { id: "m70", type: "Makale", title: "Üniversite öğrencilerinin ders çalıştıkları mekânların özellikleri", authors: "BAY ERDAL, TUĞLUK MEHMET NUR", publisher: "Atatürk Üniversitesi Dergisi", year: "2006" },
    { id: "m71", type: "Makale", title: "Üniversite öğrencilerinin ders çalışma becerilerinin incelenmesi", authors: "BAY ERDAL, TUĞLUK MEHMET NUR", publisher: "esosder", year: "2005" },
    { id: "m72", type: "Makale", title: "Okul öncesi eğitimin öğrencilerin gelişim özellikleri üzerindeki etkisi", authors: "KÖK MEHMET, BAY ERDAL", publisher: "Kazım Karabekir Dergisi", year: "2005" },
    { id: "m73", type: "Makale", title: "Gaziantep Üniversitesi Sosyal Bilimler Dergisi Makalesi", authors: "BAY ERDAL", publisher: "Gaziantep Üniversitesi", year: "2015" },
    { id: "m74", type: "Makale", title: "Eğitim Bilimlerinde Son Gelişmeler", authors: "BAY ERDAL", publisher: "Ulusal Eğitim Dergisi", year: "2004" }
  ],

  // --- 3. KATEGORİ: BİLDİRİLER (68 Adet) ---
  proceedings: [
    { id: "b1", type: "Uluslararası Özet Bildiri", title: "Investigation Of Elementary Mathematics Education Process In Terms Of Computational Thinking Skills", authors: "SOĞANCI SAADET, BAY ERDAL", conference: "International Scientific Conference “BRIDGE 2024”", location: "KOSOVA, Prizren", year: "2024" },
    { id: "b2", type: "Uluslararası Özet Bildiri", title: "Etnopedagojik Bağlamda Balkan Ülkeleri Okul Öncesi Eğitim Öğretmenlerinin Karakter Eğitimi Uygulamaları", authors: "KAYA NACİYE, ERİŞEN YAVUZ, BAY ERDAL", conference: "XI. Uluslararası Eğitim Programları ve Öğretim Kongresi", location: "TÜRKİYE, Ankara", year: "2023" },
    { id: "b3", type: "Uluslararası Tam Metin Bildiri", title: "Dilde, İşte Fikirde Birlik için eğitimde birlik: TUDVA Projesi örneği", authors: "ÖKSÜZ YÜCEL, BAY ERDAL, ULUSOY MUHAMMET AYKUTHAN, ŞİRAZ FADIL", conference: "Uluslararası Türk Dünyası Sempozyumu", location: "TÜRKİYE, Erzincan", year: "2022" },
    { id: "b4", type: "Uluslararası Tam Metin Bildiri", title: "Gençlerin Türk dünyasının dünü, bugünü ve yarınların tasavvuruna ilişkin yaklaşımları", authors: "Mamadova Konul, BAY ERDAL, KAHRAMANOĞLU RECEP", conference: "Uluslararası Türk Dünyası Sempozyumu", location: "TÜRKİYE, Erzincan", year: "2022" },
    { id: "b5", type: "Uluslararası Tam Metin Bildiri", title: "Etnopedagojik Bağlamda Balkan Ülkeleri ve Türkiye Okul Öncesi Eğitim Programlarının Karşılaştırılması", authors: "Kaya Naciye, ERİŞEN YAVUZ, BAY ERDAL", conference: "EJER Congress", location: "TÜRKİYE, Aksaray", year: "2021" },
    { id: "b6", type: "Uluslararası Özet Bildiri", title: "Pre-School And Primary School Parents’ Perception Of Covid-19 And School Perceptions", authors: "BAŞARAN MEHMET, BAY ERDAL, VURAL ÖMER FARUK", conference: "International Migration during the COVID-19 Pandemic", location: "MOĞOLİSTAN", year: "2021" },
    { id: "b7", type: "Uluslararası Tam Metin Bildiri", title: "Knowledge, Awareness And Expectations Of Turkish Students About Covid-19 Pandemic", authors: "BAY ERDAL, GÖL MEHMET, DÖŞ BÜLENT", conference: "International Migration during the COVID-19 Pandemic", location: "MOĞOLİSTAN", year: "2021" },
    { id: "b8", type: "Uluslararası Özet Bildiri", title: "THE ANALYSIS OF HOMEWORK PRACTICES IN TERMS OF PISA AND TIMSS EXAMS", authors: "ODABAŞ CEYLA, BAY ERDAL, KAHRAMANOĞLU RECEP", conference: "7th International Congress on Curriculum and Instruction", year: "2019" },
    { id: "b9", type: "Uluslararası Özet Bildiri", title: "Okul öncesinde Stem uygulamalarının okul öncesi dönemdeki çocuklar üzerinde etkisi", authors: "BAŞARAN MEHMET, BAY ERDAL", conference: "V. TURKCESS Eğitim ve Sosyal Bilimler Kongresi", year: "2019" },
    { id: "b10", type: "Uluslararası Özet Bildiri", title: "Ortaokul öğretmenlerinin teneffüs hakkındaki görüşleri", authors: "BAY ERDAL, DÖŞ BÜLENT, Tanış Yasemin", conference: "V. TURKCESS Eğitim ve Sosyal Bilimler Kongresi", location: "TÜRKİYE, İstanbul", year: "2019" },
    { id: "b11", type: "Uluslararası Özet Bildiri", title: "Okul öncesi eğitim programının karakter eğitimi açısından değerlendirilmesi", authors: "Kocalar Evrim, BAY ERDAL", conference: "V. TURKCESS Eğitim ve Sosyal Bilimler Kongresi", location: "TÜRKİYE, İstanbul", year: "2019" },
    { id: "b12", type: "Uluslararası Özet Bildiri", title: "EPALE projesi ve yetişkin eğitimi", authors: "BAY ERDAL", conference: "V. TURKCESS Eğitim ve Sosyal Bilimler Kongresi", location: "TÜRKİYE, İstanbul", year: "2019" },
    { id: "b13", type: "Uluslararası Özet Bildiri", title: "Benzerlikler ve farklılıklar stratejisinin sosyal bilgiler dersinde öğrenci başarısı üzerinde etkililiği", authors: "Duman Cevahir, BAY ERDAL", conference: "V. TURKCESS Eğitim ve Sosyal Bilimler Kongresi", location: "TÜRKİYE, İstanbul", year: "2019" },
    { id: "b14", type: "Uluslararası Tam Metin Bildiri", title: "Geleceğin Bilim İnsanı Yetiştirme Sürecinde Lisansüstü Eğitim Üzerine Bir Zihniyet Denemesi", authors: "POLAT ÜMİT, BAY ERDAL", conference: "Türkcess Kongre 2018 Azerbaycan", location: "AZERBAYCAN, Bakü", year: "2018" },
    { id: "b15", type: "Uluslararası Özet Bildiri", title: "Öğretmenlerin gerçeklik şoku", authors: "BAY ERDAL", conference: "IV. Uluslararası Türk Kültür Coğrafyasında Eğitim Sempozyumu", location: "AZERBAYCAN, Bakü", year: "2018" },
    { id: "b16", type: "Uluslararası Tam Metin Bildiri", title: "Öğretmen Yetiştiren Kurumlara Öğrenci Seçimi Bağlamında Meb Şura Kararları", authors: "KAHRAMANOĞLU RECEP, BAY ERDAL", conference: "TURKCESS 2018", year: "2018" },
    { id: "b17", type: "Uluslararası Özet Bildiri", title: "Investigation of Teacher Candidates’ Computational Thinking Skills", authors: "ÜZÜMCÜ ÖZLEM, BAY ERDAL", conference: "World Stem Education Conference", location: "TÜRKİYE, İstanbul", year: "2018" },
    { id: "b18", type: "Uluslararası Özet Bildiri", title: "Öğretmenlerin STEM'e İlişkin Metaforik Algıları Üzerine Nitel Bir Değerlendirme", authors: "BAY ERDAL, BAŞARAN MEHMET, Tıraş Meral", conference: "27th International Conference on Educational Sciences", location: "TÜRKİYE, Antalya", year: "2018" },
    { id: "b19", type: "Uluslararası Özet Bildiri", title: "Bir Okul Öncesi Eğitim Kurumu İçin Stem Eğitici Eğitimi Süreci ve Basamakları", authors: "BAŞARAN MEHMET, BAY ERDAL", conference: "27th International Conference on Educational Sciences", location: "TÜRKİYE, Antalya", year: "2018" },
    { id: "b20", type: "Uluslararası Özet Bildiri", title: "Öğretmenlik Mesleğine Yönelik Tutum Ölçeği (ÖMYTÖ) Geçerlik ve Güvenirlik Çalışması", authors: "KAHRAMANOĞLU RECEP, CÜCÜK EYÜP, BAY ERDAL", conference: "5. Uluslararası Eğitim Programları ve Öğretim Kongresi", location: "TÜRKİYE, Muğla", year: "2017" },
    { id: "b21", type: "Uluslararası Özet Bildiri", title: "Eğitim Fakültesi Birinci Sınıf Öğretmen Adaylarının Öğretmenliğe Giriş Özelliklerinin Analizi", authors: "YOKUŞ ERHAN, BAY ERDAL", conference: "5th International Congress on Curriculum and Instruction", year: "2017" },
    { id: "b22", type: "Uluslararası Özet Bildiri", title: "Analysis of Computational Thinking Unit of Information Technologies and Software Course", authors: "ÜZÜMCÜ ÖZLEM, BAY ERDAL", conference: "5th International Congress on Curriculum and Instruction", location: "TÜRKİYE, Muğla", year: "2017" },
    { id: "b23", type: "Uluslararası Özet Bildiri", title: "ENHANCING PROFESSIONAL DEVELOPMENT OF SYRIAN REFUGEE TEACHERS", authors: "BAY ERDAL, KAHRAMANOĞLU RECEP, DÖŞ BÜLENT", conference: "I. Uluslararası İpekyolu Akademik Çalışmalar Sempozyumu", location: "TÜRKİYE, Nevşehir", year: "2017" },
    { id: "b24", type: "Uluslararası Özet Bildiri", title: "Enhancing Professional Development of Syrian Refugee Teachers", authors: "BAY ERDAL, KAHRAMANOĞLU RECEP, DÖŞ BÜLENT", conference: "1. Uluslararası İpekyolu Akademik Çalışmalar Sempozyumu", year: "2017" },
    { id: "b25", type: "Uluslararası Özet Bildiri", title: "Gagne’nin Teknoloji Destekli Öğretim Etkinlikleri Modelinin Fen Bilimleri Dersinde Başarıya Etkisi", authors: "KARAKOÇ BERNA, KARA KEVSER, BAY ERDAL", conference: "2. Uluslararası Sosyal Bilimler Sempozyumu", year: "2017" },
    { id: "b26", type: "Uluslararası Özet Bildiri", title: "2015 PİSA yıldızı Singapur’un eğitim sisteminin incelenmesi", authors: "TURAN ÖZPOLAT ESEN, BAY ERDAL", conference: "II. Uluslararası Sosyal Bilimler Sempozyumu (ASOS Congress)", location: "TÜRKİYE, Alanya", year: "2017" },
    { id: "b27", type: "Uluslararası Özet Bildiri", title: "Etkili Öğretim Stratejileri Ölçeği (EÖSÖ) Geçerlik ve Güvenirlik Çalışması", authors: "CÜCÜK EYÜP, BAY ERDAL, ŞİRAZ FADIL", conference: "26. Uluslararası Eğitim Bilimleri Kongresi", location: "TÜRKİYE, Antalya", year: "2017" },
    { id: "b28", type: "Uluslararası Özet Bildiri", title: "İlköğretim Dördüncü Sınıf Sosyal Bilgiler Öğretim Programının Sosyal Girişimcilik Çerçevesi", authors: "DÖŞ BÜLENT, BAY ERDAL", conference: "4. Uluslararası Eğitim Programları ve Öğretim Kongresi", year: "2016" },
    { id: "b29", type: "Uluslararası Sözlü Bildiri", title: "Harmanlanmış bir dersin öğrencilerin başarıları motivasyonları üzerindeki etkisi", authors: "ÇIRAK SEVİLAY, BAY ERDAL", conference: "4. Uluslararası Eğitim Programları ve Öğretim Kongresi", year: "2016" },
    { id: "b30", type: "Uluslararası Özet Bildiri", title: "Cumhuriyet sonrası öğretmen yetiştiren kurumların giriş koşulları", authors: "KAHRAMANOĞLU RECEP, BAY ERDAL", conference: "4. Uluslararası Eğitim Programları ve Öğretim Kongresi", year: "2016" },
    { id: "b31", type: "Uluslararası Özet Bildiri", title: "Türk Dünyası Algı Araştırması", authors: "BAY ERDAL", conference: "4. Uluslar arası Türk Şöleni", year: "2016" },
    { id: "b32", type: "Uluslararası Özet Bildiri", title: "Etnopedagoji nin Kuramsal Çerçevesi Ve Gelişimi", authors: "Şiraz Fadıl, BAY ERDAL", conference: "II. Uluslar arası Türk Kültür Coğrafyasında Eğitim Sempozyumu", year: "2016" },
    { id: "b33", type: "Uluslararası Özet Bildiri", title: "Paradigmanın yükseliş ve çöküşünün sebepleri Niçin Nasıl", authors: "BAY ERDAL", conference: "Second International Conference On Education", year: "2016" },
    { id: "b34", type: "Uluslararası Sözlü Bildiri", title: "Determining And Evaluating The Enrollment Standards And Procedures For Teacher Training Institutions", authors: "CÜCÜK EYÜP, BAY ERDAL", conference: "ISER- 21st International Conference on Education and Social Science", year: "2016" },
    { id: "b35", type: "Uluslararası Özet Bildiri", title: "The Investigation Of Blended Learning Supported By The Quantum Learning Cycle", authors: "ÇIRAK SEVİLAY, BAY ERDAL", conference: "3rd International Congress on Curriculum and Instruction", year: "2015" },
    { id: "b36", type: "Uluslararası Özet Bildiri", title: "From The Teacher Candidates Point Of View Edmodo Social Learning Network", authors: "ÇIRAK SEVİLAY, BAY ERDAL", conference: "3rd International Congress on Curriculum and Instruction", location: "TÜRKİYE, Adana", year: "2015" },
    { id: "b37", type: "Uluslararası Özet Bildiri", title: "Neden Türk Dünyası Vatandaşlığı", authors: "BAY ERDAL", conference: "Türk Dünyası Vatandaşlığı Çalıştayı", location: "KIRGIZİSTAN, Bişkek", year: "2014" },
    { id: "b38", type: "Ulusal Sözlü Bildiri", title: "Eğitimin Sosyal İşlevi Açısından Yerel Gazetelerin İncelenmesi Adıyaman İli Örneği", authors: "TURAN ÖZPOLAT ESEN, KARA AHMET, BAY ERDAL", conference: "3.Ulusal Eğitim Programları ve Öğretim Kongresi", location: "TÜRKİYE", year: "2014" },
    { id: "b39", type: "Ulusal Sözlü Bildiri", title: "Öğretmen Yetiştiren Kurumlar İçin Giriş Standartlarının Belirlenmesi Delphi Çalışması", authors: "KAHRAMANOĞLU RECEP, BAY ERDAL", conference: "3.Ulusal Eğitim Programları ve Öğretim Kongresi", location: "TÜRKİYE", year: "2014" },
    { id: "b40", type: "Uluslararası Özet Bildiri", title: "Türk Dünyası Vatandaşlığı Ders Programının Geliştirilmesi ve etkilliğinin değerlendirilmesi", authors: "BAY ERDAL, DOĞAN AYHAN, DEMİR SERVET", conference: "I. Uluslar arası Türk Dünyası Araştırmaları Sempozyumu", location: "TÜRKİYE, Niğde", year: "2014" },
    { id: "b41", type: "Uluslararası Özet Bildiri", title: "Teachers Opinions Concerning School Based Curriculum Development", authors: "AYDIN Z, KAHRAMANOĞLU RECEP, BAY ERDAL", conference: "European Conference on Curriculum Studies", location: "PORTEKİZ, Braga", year: "2013" },
    { id: "b42", type: "Ulusal Özet Bildiri", title: "Öğretmenlerin mesleki gelişimleri bağlamında rehber öğretmenlik uygulamasının etkililiği", authors: "BAY ERDAL, KAHRAMANOĞLU RECEP, AYDIN ZEYNEP", conference: "XII Ulusal Sınıf Öğretmenliği Eğitimi Sempozyumu", location: "TÜRKİYE, Aydın", year: "2013" },
    { id: "b43", type: "Uluslararası Tam Metin Bildiri", title: "İlköğretim öğretmenlerinin ölçme değerlendirme yöntem ve tekniklerini kullanma düzeyleri", authors: "Çetin B., Delikara D., BAY Erdal, Türkan A.", conference: "3rd World Conference on Learning, Teaching and Educational Leadership", location: "BELÇİKA, Brüksel", year: "2012" },
    { id: "b44", type: "Uluslararası Tam Metin Bildiri", title: "Evaluation of secondary education programs in the context of social foundations", authors: "BAY ERDAL, CELKAN H Y", conference: "International Conference on New Horizons in Education", location: "ÇEK CUMHURİYETİ, Prag", year: "2012" },
    { id: "b45", type: "Uluslararası Tam Metin Bildiri", title: "Sosyal Yapılandırmacı öğrenme ortamlarında öğretmen adaylarının bilgi öğrenme inançları", authors: "ÇETİN BAYRAM, BAY ERDAL, TÜRKAN AZMİ", conference: "International Conference on New Horizons in Education", location: "BELÇİKA, Brüksel", year: "2012" },
    { id: "b46", type: "Uluslararası Tam Metin Bildiri", title: "Self regulatory learning strategy skills and self efficacy perceptions", authors: "OZAN CEYHUN, GÜNDOĞDU KERİM, BAY ERDAL", conference: "4th World Conference on Educational Sciences", location: "İSPANYA, Barcelona", year: "2012" },
    { id: "b47", type: "Uluslararası Tam Metin Bildiri", title: "The analysis of teacher candidates beliefs as to knowledge learning and teaching", authors: "BAY ERDAL", conference: "4th World Conference on Educational Sciences", location: "İSPANYA, Barcelona", year: "2012" },
    { id: "b48", type: "Ulusal Özet Bildiri", title: "Amerikan Alman ve Türk sınıf öğretmenlerinin karakter eğitimine ilişkin görüşlerinin incelenmesi", authors: "Gündoğdu K., Bay Erdal", conference: "Sosyal ve Kurumsal Yönleriyle Değerler Eğitimi", location: "TÜRKİYE, Eskişehir", year: "2011" },
    { id: "b49", type: "Uluslararası Tam Metin Bildiri", title: "İnsan hakları eğitiminde filmlerin kullanılması Öğretmen eğitiminde bir eylem araştırması", authors: "GÜNDOĞDU KERİM, TAŞGIN ADNAN, BAY ERDAL", conference: "I. Uluslararası Eğitim Programları ve Öğretim Kongresi", location: "Eskişehir", year: "2011" },
    { id: "b50", type: "Uluslararası Tam Metin Bildiri", title: "İlköğretim öğretmen adaylarının program yaklaşımlarının incelenmesi Atatürk Üniversitesi Örneği", authors: "BAY ERDAL, GÜNDOĞDU KERİM", conference: "Uluslararası Eğitim Programları ve Öğretim Kongresi", location: "Eskişehir", year: "2011" },
    { id: "b51", type: "Uluslararası Tam Metin Bildiri", title: "The effects of the authentic task based social constructivist approach on problem solving", authors: "BAY ERDAL, ÇETİN BAYRAM", conference: "7th Annual International Conference on Education", location: "YUNANİSTAN, Samos", year: "2011" },
    { id: "b52", type: "Uluslararası Tam Metin Bildiri", title: "Sosyal yapılandırmacı yaklaşımda işbirliği sürecinin etkililiğinin incelenmesi", authors: "BAY ERDAL, ÇETİN BAYRAM", conference: "Uluslararası 9. Bilgi, Ekonomi Ve Yönetim Kongresi", location: "BOSNA HERSEK, Saraybosna", year: "2011" },
    { id: "b53", type: "Ulusal Özet Bildiri", title: "Sınıf öğretmenlerinin çoklu zekâ kuramına ilişkin görüşlerinin incelenmesi", authors: "Ozan C., Taşgın A., Bay E., Kaya H.", conference: "19. Ulusal Eğitim Bilimleri Kongresi", location: "KKTC, Lefkoşa", year: "2010" },
    { id: "b54", type: "Ulusal Özet Bildiri", title: "Öğretmenlik mesleğinin statüsünün öğretmen adaylarının görüşleri çerçevesinde değerlendirilmesi", authors: "Kaya H.İ, Küçükoğlu A., Bay Erdal", conference: "XVI Ulusal Eğitim Bilimleri Kongresi", location: "TÜRKİYE, Tokat", year: "2010" },
    { id: "b55", type: "Uluslararası Tam Metin Bildiri", title: "Öğretmen adaylarının eski Türk eserlerine ilişkin farkındalık ve tutumlarının incelenmesi", authors: "MERT OSMAN, BAY ERDAL, ALYILMAZ SEMRA", conference: "8. Türk Dünyası Sosyal Bilimler Kongresi", location: "KIRGIZİSTAN", year: "2010" },
    { id: "b56", type: "Uluslararası Özet Bildiri", title: "Hizmet ederek öğrenme (Öğretmen eğitiminde yeni bir yaklaşım)", authors: "KÜÇÜKOĞLU ADNAN, KAYA HALİL İBRAHİM, BAY ERDAL", conference: "Uluslararası Öğretmen Yetiştirme Politikaları ve Sorunları Sempozyumu II", location: "TÜRKİYE, Ankara", year: "2010" },
    { id: "b57", type: "Uluslararası Tam Metin Bildiri", title: "Öğretim elemanı ve öğretmen adaylarının ölçme değerlendirmeye ilişkin görüşleri", authors: "BAY ERDAL, KAYA HALİL İBRAHİM, OZAN CEYHUN", conference: "Öğretmen Yetiştirme Politikaları ve Sorunları Sempozyumu II", location: "Ankara", year: "2010" },
    { id: "b58", type: "Uluslararası Tam Metin Bildiri", title: "Öğretmen adaylarının yapılandırmacı öğrenme ortamındaki öğrenen rollerine ilişkin görüşleri", authors: "BAY ERDAL, KAYA HALİL İBRAHİM, OZAN CEYHUN", conference: "Uluslararası Öğretmen Yetiştirme Politikaları ve Sorunları Sempozyumu", location: "Ankara", year: "2010" },
    { id: "b59", type: "Ulusal Tam Metin Bildiri", title: "Öğretmen eğitiminde otantik değerlendirme yaklaşımının öğrenci başarı ve tutumuna etkisi", authors: "BAY Erdal, Kaya H., Küçükoğlu A., Ozan C.", conference: "I. Ulusal Eğitim Programları ve Öğretim Kongresi", location: "TÜRKİYE", year: "2010" },
    { id: "b60", type: "Uluslararası Tam Metin Bildiri", title: "Öğretmen yetiştirmede sosyal girişimciliği ve katılımcılığı destekleyen bir yaklaşım olarak THUII", authors: "KÜÇÜKOĞLU ADNAN, BAY ERDAL, KAYA HALİL İBRAHİM", conference: "II. Uluslararası Türkiye Eğitim Araştırmaları Kongresi", location: "TÜRKİYE, Antalya", year: "2010" },
    { id: "b61", type: "Uluslararası Tam Metin Bildiri", title: "Orhun yazıtlarındaki toplumsal değerlerin öğretmen adayları tarafından algılanma düzeyi", authors: "MERT OSMAN, ALYILMAZ CENGİZ, BAY ERDAL", conference: "7. Uluslararası Türk Dünyası Sosyal Bilimler Kongresi", location: "KIRGIZİSTAN", year: "2009" },
    { id: "b62", type: "Uluslararası Tam Metin Bildiri", title: "Öğretmen adaylarının yapılandırmacı öğrenme ortamındaki öğretmen rollerine ilişkin algıları", authors: "BAY ERDAL, KAYA HALİL İBRAHİM, GÜNDOĞDU KERİM", conference: "First International Congress of Educational Research", location: "TÜRKİYE, Çanakkale", year: "2009" },
    { id: "b63", type: "Uluslararası Tam Metin Bildiri", title: "Educational philosophies of faculty staff in teacher training institutions in Turkey", authors: "GÜNDOĞDU KERİM, BAY ERDAL, KAYA HALİL İBRAHİM", conference: "International Conference on Educational Sciences 2008 (ICES’08)", location: "KKTC", year: "2008" },
    { id: "b64", type: "Uluslararası Tam Metin Bildiri", title: "Öğretmen adaylarının yapılandırmacı öğrenme ortamlarının demokratikliğine ilişkin görüşleri", authors: "BAY ERDAL, KAYA HALİL İBRAHİM, GÜNDOĞDU KERİM", conference: "Avrupa'da Demokrasi ve Demokrasi Eğitimi Uluslararası Sempozyumu", location: "TÜRKİYE, Çanakkale", year: "2008" },
    { id: "b65", type: "Uluslararası Tam Metin Bildiri", title: "Okul öncesi öğretmen adaylarının okulda şiddetin kaynağı üzerine algıları", authors: "GÜNDOĞDU KERİM, BAY ERDAL", conference: "II. Uluslararası Okul Öncesi Eğitimi Kongresi", location: "TÜRKİYE, İstanbul", year: "2007" },
    { id: "b66", type: "Ulusal Tam Metin Bildiri", title: "Erzurum da sokakta çalışan ilköğretim öğrencilerinin profili", authors: "Gençdoğan B., Bay Erdal", conference: "5. Sokakta Çalışan Çocuklar Sempozyumu", location: "TÜRKİYE, Gaziantep", year: "2006" },
    { id: "b67", type: "Uluslararası Tam Metin Bildiri", title: "Okul öncesi devam eden ve etmeyen öğrenciler arasındaki bilişsel sosyo duygusal gelişim", authors: "KÖK MEHMET, TUĞLUK MEHMET NUR, BAY ERDAL", conference: "I.Uluslararası Okulöncesi Eğitim Kongresi", location: "TÜRKİYE, İstanbul", year: "2004" },
    { id: "b68", type: "Uluslararası Tam Metin Bildiri", title: "Eğitim süreçlerinde demokratik dünya görüşlerinin oluşmasında etkili olan paradigmaların incelenmesi", authors: "KARAKAYA ŞERAFETTİN, BAY ERDAL", conference: "Uluslar Arası Demokrasi Eğitimi Sempozyumu", location: "TÜRKİYE, Çanakkale", year: "2004" },
  ],

  // --- 4. KATEGORİ: PROJELER (37 Adet) ---
  projects: [
    { id: "p1", title: "Kültürlerarası farklılıkların yönetiminde gastronominin kullanımına yönelik model önerisi: Gastrodiplomasi", role: "Araştırmacı", date: "2024", type: "ULUSLARARASI" },
    { id: "p2", title: "TIP EĞİTİMİNDE SANAL VE ARTIRILMIŞ GERÇEKLİK UYGULAMALARI", role: "Araştırmacı", date: "2021 - 2023", type: "BAP (Ulusal)" },
    { id: "p3", title: "Türk Dünyası Vatandaşlığı (TİKA)", role: "Proje Koordinatörü", date: "2014", type: "KAMU / TİKA" },
    { id: "p4", title: "Kültürlerarası Eğitim Bağlamında Türk Dünyası Vatandaşlığı Ders Programı Geliştirilmesi", role: "Proje Koordinatörü", date: "2014 - 2016", type: "ULUSLARARASI" },
    { id: "p5", title: "Kültürlerarası Eğitim Bağlamında Türk Dünyası Vatandaşlığı ve Eğitim Birliği", role: "Yürütücü", date: "2014 - 2016", type: "BAP" },
    { id: "p6", title: "Nitel Araştırmalarda Hatalar ve Çözümler", role: "Eğitmen", date: "2021", type: "TÜBİTAK" },
    { id: "p7", type: "TÜBİTAK", title: "İlköğretim bölümü okulöncesi öğretmenliği öğretim teknolojileri derslerinin uygulamalı işlenmesi", role: "Araştırmacı", date: "2002 - 2004" },
    { id: "p8", type: "TÜBİTAK", title: "Proje Süreç Eğitimi (1129B371300153)", role: "Yürütücü", date: "2014" },
    { id: "p9", type: "TÜBİTAK", title: "Köyde STEM-2", role: "Danışman", date: "2021" },
    { id: "p10", title: "Erzurum Ağrı Ardahan Kars taki Okul Öncesi Öğrencilerinin Problemleri", role: "Araştırmacı", date: "2005 - 2008", type: "BAP" },
    { id: "p11", type: "TÜBİTAK", title: "Proje Süreç Eğitimi (TÜBİTAK 2237)", role: "Proje Koordinatörü", date: "2014" },
    { id: "p12", title: "Creativity and curriculum (LLP Study Visit)", role: "Proje Koordinatörü", date: "2012", type: "AB / ULUSLARARASI" },
    { id: "p13", title: "Osmaniye Huzurevi Destekli Okul Öncesi Eğitim Modeli: Geçmişten Geleceğe", role: "Yürütücü", date: "2019 - 2021", type: "KAMU" },
    { id: "p14", title: "Türk Dünyası Eğitim Kültür ve Birliktelik", role: "Proje Koordinatörü", date: "2015", type: "KAMU" },
    { id: "p15", type: "TÜBİTAK", title: "Nitel Araştırmalarda Hatalar ve Çözümler (Ekim)", role: "Eğitmen", date: "2021" },
    { id: "p16", title: "Osmaniye Öğretmen Akademisi II. Dönem: Öğretmenlerin Mesleki Becerileri", role: "Danışman", date: "2019 - 2020", type: "KAMU" },
    { id: "p17", title: "Osmaniye Öğretmen Akademisi: Öğretmenlerin Mesleki Becerilerinin Geliştirilmesi", role: "Yürütücü", date: "2018 - 2019", type: "KAMU" },
    { id: "p18", title: "Enhancing Professional Development of Syrian Refugee Teachers (Danışmanlık)", role: "Danışman", date: "2016 - 2018", type: "ULUSLARARASI" },
    { id: "p19", title: "Enhancing Professional Development of Syrian Refugee Teachers (Yürütücülük)", role: "Yürütücü", date: "2016", type: "ULUSLARARASI" },
    { id: "p20", title: "Enhancing Professional Development of Syrian Refugee Teachers (Eğitim)", role: "Yürütücü", date: "2016", type: "ULUSLARARASI" },
    { id: "p21", title: "Gastrodiplomasi: Kültürlerarası farklılıkların yönetiminde gastronomi", role: "Araştırmacı", date: "2024", type: "ULUSLARARASI" },
    { id: "p22", title: "Türk Eğitim Sistemine İlişkin Sorun ve Öneriler", role: "Danışman", date: "2018 - 2019", type: "ULUSAL" },
    { id: "p23", title: "Türk Eğitim Sistemine İlişkin Görüş ve Öneriler (MEB Politikaları)", role: "Danışman", date: "2018", type: "ULUSAL" },
    { id: "p24", title: "Türk Eğitiminin İçinde Bulunduğu Sorunların Tespiti ve 2023 Hedefleri", role: "Danışman", date: "2018", type: "ÖZEL / KAMU" },
    { id: "p25", title: "EPALE Yetişkin Platformu", role: "Araştırmacı", date: "2019", type: "AB PROJESİ" },
    { id: "p26", type: "TÜBİTAK", title: "Öğretmen yetiştirmede otantik değerlendirmenin etkililiği", role: "Yürütücü", date: "2009 - 2010" },
    { id: "p27", title: "Osmaniye Öğretmen Akademisi II", role: "Araştırmacı", date: "2020", type: "KAMU" },
    { id: "p28", title: "Gaziantep Kültürü ve Üniversitesinin Balkanlarda Tanıtımı", role: "Yürütücü", date: "2016", type: "ULUSLARARASI" },
    { id: "p29", title: "Kosovalı Öğretmenlerin Mesleki Becerilerinin Geliştirilmesi", role: "Proje Koordinatörü", date: "2016", type: "ULUSLARARASI" },
    { id: "p30", type: "TÜBİTAK", title: "Servis şoförlerinin akreditasyonu sertifika programı", role: "Yürütücü", date: "2015" },
    { id: "p31", title: "LLP 2011-2012 Dönemi Çalışma Ziyaretleri Ev Sahipliği", role: "Yürütücü", date: "2011", type: "AB / ULUSLARARASI" },
    { id: "p32", type: "TÜBİTAK", title: "Erzurum Yöre Halkının 2011 Universiade Kış Oyunları Beklentileri", role: "Proje Koordinatörü", date: "2010 - 2011" },
    { id: "p33", type: "TÜBİTAK", title: "Eğitim süreçlerindeki paradigmatik dönüşüm çerçevesinde öğretmen eğitimi", role: "Proje Koordinatörü", date: "2008 - 2010" },
    { id: "p34", type: "TÜBİTAK", title: "Öğretmen eğitiminde otantik değerlendirme yaklaşımları (108K406)", role: "Yönetici", date: "2008 - 2010" },
    { id: "p35", type: "TÜBİTAK", title: "İlköğretimde karakter eğitiminin değerlendirilmesi", role: "Araştırmacı", date: "2007 - 2008" },
    { id: "p36", title: "Sokakta Çalışan İlköğretim Öğrencilerinin Rehabilitasyonu (LDI 089)", role: "Proje Koordinatör Yrd.", date: "2006 - 2008", type: "AB PROJESİ" },
    { id: "p37", type: "TÜBİTAK", title: "İlköğretim okulu müdürlerinin çalışma saatlerinin değerlendirme biçimleri", role: "Araştırmacı", date: "2003 - 2004" }
  ],

  // --- 5. KATEGORİ: ÜNİVERSİTE DIŞI DENEYİM (4 Adet) ---
  externalExperience: [
    { id: "e1", title: "TBMM KEFEK Komisyonu ”Kız çocukları başta olmak üzere gençlerin BTMM alanlarına yönlendirilmesi” rapor yazımı", role: "Uzman", place: "TÜRKİYE BÜYÜK MİLLET MECLİSİ BAŞKANLIĞI", year: "2020 - 2021" },
    { id: "e2", title: "Aile, Kadın Sağlık ve Sosyal Politikalar Kurulu Üyeliği", role: "Kurul Üyesi", place: "Gaziantep Büyükşehir Belediyesi", year: "2020" },
    { id: "e3", title: "Eğitim Bilimleri Öğretim Üyesi", role: "Öğretim Üyesi", place: "Ukshin Hoti Üniversitesi", year: "2024" },
    { id: "e4", title: "Gaziantep Kent Konseyi", role: "Yürütme Kurulu Üyesi", place: "Gaziantep Kent Konseyi", year: "2024" }
  ],

  // --- 6. KATEGORİ: EDİTÖRLÜKLER (26 Adet) ---
  editorships: [
    { id: "ed1", title: "Fen Bilgisi Eğitimi alanında araştırmalar ve değerlendirmeler", type: "Kitap", publisher: "Gece", year: "2024" },
    { id: "ed2", title: "Türk Dünyasının Eğitim Sistemleri ve Sorunları", type: "Kitap", publisher: "Pegem", year: "2017" },
    { id: "ed3", title: "Eğitim Bilimleri Alanında Akademik Çalışmalar", type: "Kitap", publisher: "GECE KİTAPLIĞI", year: "2023" },
    { id: "ed4", title: "Eğitim Bilimler Alanında Uluslararası Araştırmalar ve Değerlendirmeler", type: "Kitap", publisher: "Serüven", year: "2023" },
    { id: "ed5", title: "Eğitim Bilimlerinde Uluslararası Çalışmalar", type: "Kitap", publisher: "Serüven", year: "2023" },
    { id: "ed6", title: "Z Kuşağı Ethosfer Sisteminin Analizi (Z’amane Kuşağını Anlama)", type: "Kitap", publisher: "GAZİ KÜLTÜR", year: "2023" },
    { id: "ed7", title: "Academic Studies in Educational Sciences", type: "Kitap", publisher: "GECE KİTAPLIĞI", year: "2023" },
    { id: "ed8", title: "Etkili Öğretim Stratejileri", type: "Kitap", publisher: "Pegem Akademi", year: "2022" },
    { id: "ed9", title: "International Research in Educational Sciences", type: "Kitap", publisher: "Serüven", year: "2022" },
    { id: "ed10", title: "Eğitim Bilimlerinde Uluslararası Araştırmalar – II", type: "Kitap", publisher: "Serüven", year: "2022" },
    { id: "ed11", title: "Eğitim Bilimlerinde Uluslararası Araştırmalar – I", type: "Kitap", publisher: "Serüven", year: "2022" },
    { id: "ed12", title: "5. Uluslararası Turkcess Eğitim ve Sosyal Bilimler Kongresi", type: "Kitap", publisher: "TEBAD", year: "2019" },
    { id: "ed13", title: "IV. ULUSLARARASI TÜRK KÜLTÜR COĞRAFYASINDA EĞİTİM SEMPOZYUMU", type: "Diğer", publisher: "Tebad", year: "2018" },
    { id: "ed14", title: "Uluslararası Türk Kültür Coğrafyasında Sosyal Bilimler Dergisi", type: "Dergi", publisher: "TEBAD", year: "2018" },
    { id: "ed15", title: "Reform ve değişim Bağlamında İlkokul Matematik Öğretim Programları", type: "Kitap", publisher: "Pegem", year: "2016" },
    { id: "ed16", title: "Kız çocukları Başta Olmak üzere Gençlerin BTMM Alanlarına Yönlendirilmesi Raporu", type: "Kitap", publisher: "TBMM", year: "2020" },
    { id: "ed17", title: "Anadolu Türk Eğitim Dergisi", type: "Dergi", publisher: "Bireysel", year: "2020" },
    { id: "ed18", title: "Türk İslam Dünyası Sosyal Araştırmalar Dergisi", type: "Dergi", publisher: "Yüzüncü Yıl Üniversitesi", year: "2019" },
    { id: "ed19", title: "AnadoluTürk Eğitim Dergisi", type: "Dergi", publisher: "Bireysel", year: "2019" },
    { id: "ed20", title: "Uluslararası Eğitimde Yenilikçi Yaklaşımlar Dergisi (2018)", type: "Dergi", publisher: "Pen Academic Publishing", year: "2018" },
    { id: "ed21", title: "Uluslararası Eğitimde Yenilikçi Yaklaşımlar Dergisi (2019)", type: "Dergi", publisher: "Pen Academic Publishing", year: "2019" },
    { id: "ed22", title: "Uluslararası Türk Kültür Coğrafyasında Sosyal Bilimler Dergisi", type: "Dergi", publisher: "Niğde Ömer Halisdemir Üniversitesi", year: "2017" },
    { id: "ed23", title: "Türk Dünyasının Eğitim Sistemleri ve Sorunları", type: "Kitap", publisher: "Pegem", year: "2017" },
    { id: "ed24", title: "Reform ve değişim Bağlamında İlkokul Matematik Öğretim Programları", type: "Kitap", publisher: "Pegem", year: "2016" },
    { id: "ed25", title: "Gaziantep University Journal of Social Sciences", type: "Dergi", publisher: "Gaziantep Üniversitesi", year: "2015" },
    { id: "ed26", title: "Gaziantep Eğitim Tarihini Konuşturan Fotoğraflar", type: "Kitap", publisher: "Üniversite Vakfı yayınları", year: "2013" }
  ], 

  // --- 7. KATEGORİ: ARAŞTIRMALAR & ETKİNLİKLER (21 Adet) ---
  researches: [
    { id: "r1", title: "2. & 4. Türk Kültür Coğrafyasında Eğitim ve Sosyal Bilimler Kongresi", type: "Kongre Düzenleme", place: "AZERBAYCAN", role: "Düzenleyici", year: "Uluslararası" },
    { id: "r2", title: "V. TURKCESS Uluslararası Eğitim ve Sosyal Bilimler Kongresi", type: "Kongre Düzenleme", place: "Yıldız Teknik Üniversitesi", role: "Düzenleyici", year: "Uluslararası" },
    { id: "r3", title: "Öğretmen eğitiminde kalite arayışı", type: "Çalıştay", place: "Adana, Türkiye", role: "Katılımcı", year: "Ulusal" },
    { id: "r4", title: "Türk Dünyası ve Gelecek için eğitim", type: "Konuşma", place: "KOSOVA (Nisan Kosova Türkleri Milli Bayramı)", role: "Konuşmacı", year: "Ulusal" },
    { id: "r5", title: "Türk Dünyası Vatandaşlığı", type: "Çalıştay", place: "Bişkek, Kırgızistan", role: "Katılımcı", year: "Uluslararası" },
    { id: "r6", title: "Eğitimde yapılandırmacılık", type: "Seminer", place: "GAZİANTEP", role: "Eğitmen", year: "Ulusal" },
    { id: "r7", title: "Ulusal Sosyal Bilgiler Eğitimi Çalıştayı", type: "Çalıştay", place: "Gaziantep, Türkiye", role: "Katılımcı", year: "Ulusal" },
    { id: "r8", title: "Dijital Çağda Öğretmenlik", type: "Çalıştay", place: "Prizren, Kosova", role: "Katılımcı", year: "Uluslararası" },
    { id: "r9", title: "Sınıf ortamında öğretim becerileri", type: "Seminer", place: "Kâzım Karabekir Eğitim Fakültesi", role: "Eğitmen", year: "Ulusal" },
    { id: "r10", title: "Eğitim mi eritim mi?", type: "Konuşma", place: "Nizip Ticaret Odası, GAZİANTEP", role: "Konuşmacı", year: "Ulusal" },
    { id: "r11", title: "Etkili Öğretmenlik", type: "Konuşma", place: "Osmaniye Öğretmen Akademisi", role: "Konuşmacı", year: "Ulusal" },
    { id: "r12", title: "Geçmişten günümüze fotoğraflarla eğitim", type: "Seminer", place: "KKEF Konferans Salonu, GAZİANTEP", role: "Eğitmen", year: "Ulusal" },
    { id: "r13", title: "3. II. Uluslararası Türk Dünyası Eğitim Bilimleri ve Sosyal Bilimler Kongresi", type: "Kongre Düzenleme", place: "GAZİANTEP", role: "Düzenleyici", year: "Uluslararası" },
    { id: "r14", title: "Geçmişten günümüze fotoğraflarla eğitim (GAÜN)", type: "Seminer", place: "GAZİANTEP ÜNİVERSİTESİ", role: "Eğitmen", year: "Ulusal" },
    { id: "r15", title: "Zaim Başaslanla Z'den A'ya (Kosovalı Öğretmenler Projesi)", type: "TV Röportajı", place: "BaharTürk TV, Gaziantep", role: "Konuk", year: "Ulusal" },
    { id: "r16", title: "Türk Dünyası Eğitim Kültür Birliktelik", type: "Çalıştay", place: "Macaristan-Avusturya-Slovakya", role: "Katılımcı", year: "Uluslararası" },
    { id: "r17", title: "OSYM Bina Sorumluları Eğiticilerin Eğitimi", type: "Kurs", place: "Gaziantep Üniversitesi", role: "Eğitmen/Katılımcı", year: "Ulusal" },
    { id: "r18", title: "Proje Süreç Yönetimi (UNDP/Doğu Anadolu Kalkınma Programı)", type: "Sertifika", place: "Erzurum", role: "Katılımcı", year: "Ulusal" },
    { id: "r19", title: "Eğitim mi eritim mi? (Türk Ocakları)", type: "Konuşma", place: "Gaziantep Türk Ocakları Şubesi", role: "Konuşmacı", year: "Ulusal" },
    { id: "r20", title: "Kız çocukları başta olmak üzere gençlerin BTMM Alanlarına yönlendirilmesi raporu", type: "Araştırma Raporu", place: "Türkiye", role: "Araştırmacı", year: "Ulusal" },
    { id: "r21", title: "Eğitim sorunları (Zaim Başaslanla Z den A’ya)", type: "TV Röportajı", place: "Kanal 5, Gaziantep", role: "Konuk", year: "Ulusal" }
  ] , 
  // --- 8. KATEGORİ: ÜYELİKLER (8 Adet) ---
  memberships: [
    { id: "u1", org: "TTO (Teknoloji Transfer Ofisi)", role: "Yönetim Kurulu Üyesi", type: "Bilimsel Kuruluş", year: "2020" },
    { id: "u2", org: "Türkiye Curling Federasyonu", role: "Üye (Dış ilişkiler komisyon üyesi)", type: "Federasyon", year: "2016" },
    { id: "u3", org: "Gaziantep Üniversitesi Okul Projesi Komisyonu", role: "Başkan", type: "Bilimsel Kuruluş", year: "2016" },
    { id: "u4", org: "American Educational Research Association", role: "Üye", type: "Bilimsel Kuruluş", year: "2015" },
    { id: "u5", org: "Eğitim Programları ve Öğretim Derneği", role: "Yönetim Kurulu Üyesi", type: "Bilimsel Kuruluş", year: "2014" },
    { id: "u6", org: "Seçkin Okulları", role: "Danışman", type: "Kurum", year: "2014" },
    { id: "u7", org: "EPODER", role: "Üye", type: "Bilimsel Kuruluş", year: "2013" },
    { id: "u8", org: "Gaziantep Türk Ocakları", role: "Yönetim Kurulu Üyesi", type: "STK", year: "2012" }
  ] ,
  // --- 9. KATEGORİ: YÖNETİLEN TEZLER (26 Adet) ---
  theses: [
    // DOKTORA TEZLERİ
    { id: "dt1", title: "Etnopedagoji yaklaşımı bağlamında Balkan ülkeleri ve Türkiye'nin okul öncesi ethosferinde karakter eğitimini 'anlama'", student: "NACİYE KAYA", year: "2023", level: "Doktora", status: "Tamamlandı" },
    { id: "dt2", title: "Türkiye'de program değerlendirme alanındaki yaklaşımların analizi", student: "ESRA DOĞAN", year: "2022", level: "Doktora", status: "Tamamlandı" },
    { id: "dt3", title: "Politik bir metin olarak sosyal bilgiler öğretim programlarını vatandaşlık eğitimi bağlamında anlama", student: "FADIL ŞİRAZ", year: "2020", level: "Doktora", status: "Tamamlandı" },
    { id: "dt4", title: "Bilgi işlemsel düşünme becerisine yönelik program tasarımının geliştirilmesi ve etkililiğinin değerlendirilmesi", student: "ÖZLEM ÜZÜMCÜ", year: "2019", level: "Doktora", status: "Tamamlandı" },
    { id: "dt5", title: "Okul öncesi eğitimde STEM yaklaşımının uygulanabilirliği (Eylem araştırması)", student: "MEHMET BAŞARAN", year: "2018", level: "Doktora", status: "Tamamlandı" },
    { id: "dt6", title: "Matematik dersinde otantik görev odaklı öğrenme süreçlerinin incelenmesi: Bir eylem araştırması", student: "ZEYNEP AYDIN AŞK", year: "2016", level: "Doktora", status: "Tamamlandı" },
    { id: "dt7", title: "Kuantum öğrenme döngüsü ile desteklenen harmanlanmış öğrenmenin etkililiği üzerine bir araştırma", student: "SEVİLAY ÇIRAK", year: "2016", level: "Doktora", status: "Tamamlandı" },
    { id: "dt8", title: "Otantik görev odaklı uygulamaların yabancı dil eğitimine etkisinin incelenmesi", student: "BERNA KARAKOÇ", year: "2016", level: "Doktora", status: "Tamamlandı" },
    { id: "dt9", title: "Fen bilimleri dersinde etkili öğretim stratejilerinin etkililiğinin değerlendirilmesi", student: "KEVSER KARA", year: "2016", level: "Doktora", status: "Tamamlandı" },
    { id: "dt10", title: "Öğretmenlerin program uyumluluğu ve program uyumluluğunu etkileyen faktörlerin analizi", student: "ESEN TURAN ÖZPOLAT", year: "2015", level: "Doktora", status: "Tamamlandı" },
    { id: "dt11", title: "Öğretmen yetiştiren kurumlara öğrenci seçiminde kullanılacak giriş standartları ve ölçülebilirliği", student: "RECEP KAHRAMONOĞLU", year: "2014", level: "Doktora", status: "Tamamlandı" },

    // YÜKSEK LİSANS TEZLERİ
    { id: "yl1", title: "Öğretmenlerin eğitim araştırmalarına yönelik tutumlarıyla öğretim programlarındaki değişime uyumları arasındaki ilişki", student: "TANER ŞEN", year: "2025", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl2", title: "İlköğretim matematik öğretim programının bilgi işlemsel düşünme becerisi açısından incelenmesi", student: "SAADET SOĞANCI", year: "2024", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl3", title: "Ödev niteliğinin öğrenmeye katkısının değerlendirilmesi: Bir eylem araştırması", student: "CANSU ÖZTAŞ", year: "2023", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl4", title: "Yabancı dil olarak İngilizce öğretimi alanındaki araştırma eğilimleri", student: "ELVAN ACIROĞLU", year: "2020", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl5", title: "Benzerlikler ve farklılıklar stratejisinin sosyal bilgiler dersinde öğrenci başarısı üzerinde etkililiği", student: "CEVAHİR DUMAN", year: "2019", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl6", title: "2013 okul öncesi eğitim programının karakter eğitimi açısından değerlendirilmesi", student: "EVRİM KOCALAR", year: "2019", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl7", title: "Coğrafya öğretmenlerinin etkili öğretim stratejileri", student: "IBTISAM AHMED JASIM JASIM", year: "2018", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl8", title: "İngilizce öğretmenlerinin Eğitim Bilişim Ağı (EBA) kullanım durumlarının incelenmesi", student: "MUHAMMET ESAD KULOĞLU", year: "2018", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl9", title: "Türkiye ve Rusya'daki İngilizce öğretmenlerinin etkili öğretim stratejilerine ilişkin yaklaşımları", student: "ALEKSANDRA ÇELİK", year: "2018", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl10", title: "Yabancı dil olarak İngilizce öğretiminde etkili öğretim stratejilerin analizi", student: "HATUN BUĞRA ALTUNÖZ", year: "2017", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl11", title: "Üçüncü sınıf fen bilimleri dersi öğretim programının öğretmen görüşleri doğrultusunda değerlendirilmesi", student: "İSMAİL BAŞIBEYAZ", year: "2016", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl12", title: "Tanzimat'tan Cumhuriyet'e öğretmen yetiştiren kurumlara giriş şartları ile usûllerinin belirlenmesi", student: "EYÜP CÜCÜK", year: "2015", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl13", title: "Eğitim fakültesi birinci sınıf öğretmen adaylarının öğretmenliğe giriş özelliklerinin analizi", student: "ERHAN YOKUŞ", year: "2015", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl14", title: "Öğretmenlerin öğretim program yaklaşımlarının analizi: Ankara ili örneği", student: "BİRGÜL AKTEMUR", year: "2014", level: "Yüksek Lisans", status: "Tamamlandı" },
    { id: "yl15", title: "5E modelinin ilköğretim 6. sınıf öğrencilerinin matematik dersi kümeler konusundaki erişi ve kalıcılığına etkisi", student: "AYŞE ŞAHİNER", year: "2013", level: "Yüksek Lisans", status: "Tamamlandı" }
  ]
};